# .pre-commit-config.yaml
# rev (バージョン管理) を不要にするため、ローカル環境のツールを使用します。
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude --fix
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types: [python]
        require_serial: true

      - id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        language: system
